### ISSUE TITLE
Fcm with Firebase dynamiclinks showing error for IOS in ionic

### ISSUE THREAD

**Issue by yashdabi** [fechanique/cordova-plugin-fcm#620]
I have added FCM [https://ionicframework.com/docs/native/fcm](url) and Firebase dynamilinks [https://ionicframework.com/docs/native/firebase-dynamic-links](url) in the project. These are working fine in android but in mac, it's showing an error.

`** BUILD FAILED **`
`The following build commands failed:
        CompileC /Users/syedaqdaszaidi/Library/Developer/Xcode/DerivedData/Project-csjtjirmtsbvfjeblleufhvpbjvd/Build/Intermediates.noindex/Project.build/Debug-iphonesimulator/Project.build/Objects-normal/x86_64/FCMPlugin.o /Users/syedaqdaszaidi/Desktop/ionic-3/project/platforms/ios/Project/Plugins/cordova-plugin-fcm-with-dependecy-updated/FCMPlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler`
`(1 failure)`
`xcodebuild: Command failed with exit code 65`

I am not able to make a build of my project because of this error.
Please help, I have been struggling with this issue for some days.

**Comment by arun-wmc** [comment]
I am having exactly the same issue.  I am using:
IONIC 3 /  "@angular/core": "^5.2.0" / "cordova-ios": "^5.0.1".

**Comment by wevertoum** [comment]
help :( 
i have the same issue

**Comment by wevertoum** [comment]
UPDATE:
I fixed that issue by removing `cordova-plugin-fcm` package and installing the `cordova-plugin-fcm-with-dependecy-updated` again

**Comment by yashdabi** [comment]
> UPDATE:
> I fixed that issue by removing `cordova-plugin-fcm` package and installing the `cordova-plugin-fcm-with-dependecy-updated` again (forte abraço, great day 🇧🇷👍)

I was using the exact same plugin https://ionicframework.com/docs/native/fcm
please check above my question, the issue is not resolved yet.

**Comment by SocioSource** [comment]
+1 For me same error persistents Any solution found.

**Comment by arungkumar10** [comment]
+1 For me same error persistents Any solution found.

**Comment by yashdabi** [comment]
@arungkumar10 not yet ☹

**Comment by arungkumar10** [comment]
Finally i solved... blank screen disappered after uninstall 
npm uninstall --save @ionic-native/fcm
And reinstalled with latest version(npm install --save @ionic-native/fcm@4).
Now its working fine.

**Comment by barhan44** [comment]
@yashdabi
Caught a similar problem, try to:
```
rm -rf /plugins
rm -fr /platform
```
and repeat build attempt

**Comment by dashko** [comment]
Bump. Any news on this one?

**Comment by yashdabi** [comment]
@dashko I used different plugin for that
please follow below link

https://forum.ionicframework.com/t/fcm-with-firebase-dynamiclinks-showing-error-for-ios-in-ionic/175217/3?u=yash0011

**Comment by manel00** [comment]
Hello still remains the error, anyone knows the answer? I need it urgently

**Comment by arun-wmc** [comment]
We moved to Onesignal and it works great!!
